#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum TicketPaymentError {
    AlreadyInitialized = 1,
    InvalidAddress = 2,
    NotInitialized = 3,
    EventNotFound = 4,
    EventInactive = 5,
    TokenNotWhitelisted = 6,
    MaxSupplyExceeded = 7,
    PaymentNotFound = 8,
    InvalidPaymentStatus = 9,
    TicketNotRefundable = 10,
    TierNotFound = 11,
    InsufficientAllowance = 12,
    TransferVerificationFailed = 13,
    ArithmeticError = 14,
    SelfReferralNotAllowed = 15,
    PriceMismatch = 16,
    InvalidPrice = 17,
    InvalidDiscountCode = 18,
    DiscountCodeUsed = 19,
    Unauthorized = 20,
    EventNotCompleted = 21,
    NoFundsAvailable = 22,
    RefundDeadlinePassed = 23,
    WithdrawalCapExceeded = 24,
    InsufficientFees = 25,
    ResalePriceExceedsCap = 26,
    ContractPaused = 27,
    EventCancelled = 35,
    EventDisputed = 36,
    UnauthorizedScanner = 37,
    TicketAlreadyUsed = 38,
    GoalNotMet = 39,
    OracleNotConfigured = 40,
    OraclePriceUnavailable = 41,
    PriceOutsideSlippage = 42,
    InvalidSlippageBps = 43,
    AuctionNotActive = 44,
    BidTooLow = 45,
    AuctionEnded = 46,
    AuctionNotEnded = 47,
    NotAuctionTier = 48,
    NotGovernor = 49,
    InvalidProposal = 50,
    ProposalNotActive = 51,
    AlreadyVoted = 52,
    VotingPeriodNotMet = 53,
    InsufficientVotes = 54,
    ProposalExpired = 55,
    OraclePriceStale = 56,
    CannotRemoveLastGovernor = 57,
    InvalidFeePercent = 58,
}

impl From<TicketPaymentError> for soroban_sdk::Error {
    fn from(err: TicketPaymentError) -> soroban_sdk::Error {
        soroban_sdk::Error::from_contract_error(err as u32)
    }
}

impl From<&TicketPaymentError> for soroban_sdk::Error {
    fn from(err: &TicketPaymentError) -> soroban_sdk::Error {
        soroban_sdk::Error::from_contract_error(*err as u32)
    }
}

impl From<soroban_sdk::Error> for TicketPaymentError {
    fn from(err: soroban_sdk::Error) -> TicketPaymentError {
        match err.get_code() {
            1 => TicketPaymentError::AlreadyInitialized,
            2 => TicketPaymentError::InvalidAddress,
            3 => TicketPaymentError::NotInitialized,
            4 => TicketPaymentError::EventNotFound,
            5 => TicketPaymentError::EventInactive,
            6 => TicketPaymentError::TokenNotWhitelisted,
            7 => TicketPaymentError::MaxSupplyExceeded,
            8 => TicketPaymentError::PaymentNotFound,
            9 => TicketPaymentError::InvalidPaymentStatus,
            10 => TicketPaymentError::TicketNotRefundable,
            11 => TicketPaymentError::TierNotFound,
            12 => TicketPaymentError::InsufficientAllowance,
            13 => TicketPaymentError::TransferVerificationFailed,
            14 => TicketPaymentError::ArithmeticError,
            15 => TicketPaymentError::SelfReferralNotAllowed,
            16 => TicketPaymentError::PriceMismatch,
            17 => TicketPaymentError::InvalidPrice,
            18 => TicketPaymentError::InvalidDiscountCode,
            19 => TicketPaymentError::DiscountCodeUsed,
            20 => TicketPaymentError::Unauthorized,
            21 => TicketPaymentError::EventNotCompleted,
            22 => TicketPaymentError::NoFundsAvailable,
            23 => TicketPaymentError::RefundDeadlinePassed,
            24 => TicketPaymentError::WithdrawalCapExceeded,
            25 => TicketPaymentError::InsufficientFees,
            26 => TicketPaymentError::ResalePriceExceedsCap,
            27 => TicketPaymentError::ContractPaused,
            35 => TicketPaymentError::EventCancelled,
            36 => TicketPaymentError::EventDisputed,
            37 => TicketPaymentError::UnauthorizedScanner,
            38 => TicketPaymentError::TicketAlreadyUsed,
            39 => TicketPaymentError::GoalNotMet,
            40 => TicketPaymentError::OracleNotConfigured,
            41 => TicketPaymentError::OraclePriceUnavailable,
            42 => TicketPaymentError::PriceOutsideSlippage,
            43 => TicketPaymentError::InvalidSlippageBps,
            44 => TicketPaymentError::AuctionNotActive,
            45 => TicketPaymentError::BidTooLow,
            46 => TicketPaymentError::AuctionEnded,
            47 => TicketPaymentError::AuctionNotEnded,
            48 => TicketPaymentError::NotAuctionTier,
            49 => TicketPaymentError::NotGovernor,
            50 => TicketPaymentError::InvalidProposal,
            51 => TicketPaymentError::ProposalNotActive,
            52 => TicketPaymentError::AlreadyVoted,
            53 => TicketPaymentError::VotingPeriodNotMet,
            54 => TicketPaymentError::InsufficientVotes,
            55 => TicketPaymentError::ProposalExpired,
            56 => TicketPaymentError::OraclePriceStale,
            57 => TicketPaymentError::CannotRemoveLastGovernor,
            58 => TicketPaymentError::InvalidFeePercent,
            _ => TicketPaymentError::ArithmeticError,
        }
    }
}
